import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App Blog",
  description: "Generated by create next app blog",
};

export default function BlogLayout({
  children,
  user,
  analytic,
}: {
  children: React.ReactNode
  user: React.ReactNode
  analytic: React.ReactNode
}) {
    return (
      <div>
        <nav>
          <h1>NAVBAR</h1>
        </nav>
        <div>
          {children}
        </div>
        <div>
          {user}
        </div>
        <div>
          {analytic}
        </div>
      </div>
    )
}